BEGIN;

DROP TABLE IF EXISTS users, posts, comments CASCADE;

CREATE TABLE users(
id SERIAL PRIMARY KEY,
user_name VARCHAR(250) NOT NULL,
user_email VARCHAR(250) not null  UNIQUE,
user_password VARCHAR(250) not null
);

CREATE TABLE posts(
id SERIAL PRIMARY KEY,
post_text TEXT NOT NULL,
posted_at_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
users_id INTEGER REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE comments(
id SERIAL PRIMARY KEY,
comment_text_content text NOT NULL,
commented_at_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
users_id INTEGER REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
post_id INTEGER REFERENCES posts(id) ON DELETE CASCADE ON UPDATE CASCADE
);

COMMIT;

